BlueDiamond/BlueDiamond/Components/NavigationViewComponent.cs
using BlueDiamond.Models;
using BlueDiamond.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlueDiamond.Components
{
    public class NavigationViewComponent : ViewComponent
    {
        private IProductRepository repository;
        public NavigationViewComponent(IProductRepository repo)
        {
            repository = repo;
        }

        public IViewComponentResult Invoke()
        {
            return View(repository.Products
                .SelectMany(p => p.Categories.Select(n => n.Name))
                .Distinct()
                .OrderBy(c => c));
        }
    }
}

BlueDiamond/BlueDiamond/Controllers/CartController.cs
using BlueDiamond.Models;
using BlueDiamond.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlueDiamond.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private Cart cart;

        public CartController(IProductRepository repo, Cart cartService)
        {
            repository = repo;
            cart = cartService;
        }

        public RedirectToActionResult ShowCart()
        {
            if (cart.Positions.Count() == 0)
            {
                return RedirectToAction("EmptyCart");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
        public ViewResult EmptyCart()
        {
            return View();
        }

        public ViewResult Index()
        {
            return View(cart);
        }

        public RedirectToActionResult AddToCart(int ID)
        {
            Product product = FindProductByID(ID);
            if (product != null)
            {
                cart.AddItem(product, 1);
            }

            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromCart(int ID)
        {
            Product product = FindProductByID(ID);
            if (product != null)
            {
                cart.RemoveItem(product);
            }

            return RedirectToAction("ShowCart");
        }

        [HttpGet]
        public RedirectToActionResult GetImageFile(int productID, bool horizontal = false)
        {
            return RedirectToAction("GetImageFile", "Product", new { productID = productID, horizontal = horizontal});
        }

        private Product FindProductByID(int productID)
        {
            return repository.Products.ToList().FirstOrDefault(p => p.ID == productID);
        }
    }
}

BlueDiamond/BlueDiamond/Views/Shared/CartPosition.cshtml
@model OrderPosition

<div class="row justify-content-center align-items-center" >
    <div class="col-2">
        <img src="@Url.Action("GetImageFile", new { productID = this.Model.Product.ID})" style="width: 100px; height:100px;">
        <p>@Model.Product.Name</p>
    </div>
    <div class="col-2">
        <p>@Model.Quantity</p>
    </div>
    <div class="col-2">
        <p>@Model.Product.Price.ToString("c")</p>
    </div>
    <div class="col-2">
        <p>@Model.Sum</p>
    </div>
    <div class="col-2">
        <form asp-action="RemoveFromCart" method="post">
            <input type="hidden" name="ID" value="@Model.Product.ID"/>
            <button type="submit" class="btn btn-light" data-toggle="button" aria-pressed="true"
                    autocomplete="off">
                Usuń
            </button>
        </form>
    </div>
</div>

BlueDiamond/BlueDiamond/Views/Shared/ProductDetails.cshtml
@model Product

<div class="col-sm">
    <img src="./images/background7.png" />
    <div class="container">
        <div class="row m-2">
            <p class="mr-1 mt-3">@Model.Name</p>
            <strong class=" ml-auto mt-3">@Model.Price.ToString("c")</strong>
            <form id="@Model.ID" asp-action="AddToCart" asp-controller="Cart" method="post">
                <input type="hidden" asp-for="ID"/>
                <button type="submit"
                        class="btn btn-light ml-auto mt-2"
                        style="height: 4vh;"
                        data-toggle="button"
                        aria-pressed="true"
                        autocomplete="off">
                    <i class="fas fa-shopping-basket" style="color: black;"></i>
                </button>
            </form>
        </div>
    </div>
</div>

BlueDiamond/BlueDiamond/Views/Shared/ProductSummary.cshtml
@model Product

<div class="ml-5">
    <a asp-controller="Product" asp-action="ProductDetails"  asp-route-ID="@Model.ID">
        <img src="@Url.Action("GetImageFile", new { productID = this.Model.ID})" style="width: 300px; height: 300px;" >
    </a>
    <div class="container">
        <div class="row m-2">
            <p class="mr-1 mt-3">@Model.Name</p>
            <strong class=" ml-auto mt-3">@Model.Price.ToString("c")</strong>
            <form id="@Model.ID" class="ml-2" asp-action="AddToCart" asp-controller="Cart" method="post">
                <input type="hidden" asp-for="ID" />
                <button type="submit"
                        class="btn btn-light ml-auto mt-2"
                        style="height: 5vh;"
                        data-toggle="button"
                        aria-pressed="true"
                        autocomplete="off">
                    <i class="fas fa-shopping-basket" style="color: black;"></i>
                </button>
            </form>
        </div>
    </div>
</div>

BlueDiamond/BlueDiamond/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://kit.fontawesome.com/7544a25eba.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="~/css/Styles.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Blue Diamond</title>
</head>
<body>
    <div>
        @await Component.InvokeAsync("Navigation");
    </div>
    <div>
        @RenderBody()
    </div>
    <div class="page-footer   bg-light">
        <div class="container">
            <div class="row">
                <div class="footer-col-rt col-md-6 text-center">
                    <h4>Informacje</h4>
                    <ul class="list-unstyled">
                        <li><a class="text-secondary" href="/">Pomoc</a></li>
                        <li><a class="text-secondary" href="/">Regulamin</a></li>
                        <li><a class="text-secondary" href="/">Polityka prywatności</a></li>
                    </ul>
                </div>
                <div class="footer-col-lf col-md-6 text-center">
                    <h4>Kontakt</h4>
                    <ul class="list-unstyled">
                        <li>38 716 92 91</li>
                        <li>sklep@bluediamond.pl</li>
                        <li>Katowice ul. Niebieska 8</li>
                    </ul>
                </div>
            </div>
            <div class="footer-bottom">
                <p class="text-center"> &copy;2020</p>
            </div>
        </div>

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
                integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
                integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
                integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
                crossorigin="anonymous"></script>
</body>
</html>